server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amortization_db
    username: amortization_user
    password: amortization_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
